import React from "react";
import MarkdownViewer from "./MarkdownViewer";

interface AIAnswerCardProps {
  aiAnswer: string;
}

const AIAnswerCard: React.FC<AIAnswerCardProps> = ({ aiAnswer }) => {
  return (
    <div
      className="glass-container fade-in"
      style={{
        marginBottom: "2rem",
        border: "1px solid var(--accent-color)",
        background: "rgba(56, 189, 248, 0.05)",
        padding: "1.5rem",
        borderRadius: "12px",
        boxShadow:
          "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      }}
    >
      <h3
        style={{
          color: "var(--accent-color)",
          marginTop: 0,
          display: "flex",
          alignItems: "center",
          gap: "0.5rem",
          fontSize: "1.2rem",
          marginBottom: "1rem",
        }}
      >
        <span>✨</span> AI Insight
      </h3>
      <div style={{ color: "var(--text-primary)", lineHeight: "1.6" }}>
        <MarkdownViewer
          content={aiAnswer}
          style={{ background: "transparent", padding: 0 }}
        />
      </div>
      <div
        style={{
          marginTop: "1rem",
          fontSize: "0.8rem",
          color: "var(--text-secondary)",
          borderTop: "1px solid var(--glass-border)",
          paddingTop: "0.5rem",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <span>Generated by local LLM (Ollama) based on search results.</span>
        <span style={{ fontSize: "0.7rem", opacity: 0.7 }}>
          Model: Nemotron-3 (30b-cloud)
        </span>
      </div>
    </div>
  );
};

export default AIAnswerCard;
