import React from "react";
import MarkdownViewer from "./MarkdownViewer";

interface AIAnswerCardProps {
  aiAnswer: string;
}

const AIAnswerCard: React.FC<AIAnswerCardProps> = ({ aiAnswer }) => {
  return (
    <div className="glass-container fade-in mb-8 border border-accent-color bg-sky-500/5 p-6 rounded-xl shadow-md">
      <h3 className="text-accent-color mt-0 flex items-center gap-2 text-xl mb-4">
        <span>✨</span> AI Insight
      </h3>
      <div className="text-text-primary leading-relaxed">
        <MarkdownViewer
          content={aiAnswer}
          style={{ background: "transparent", padding: 0 }}
        />
      </div>
      <div className="mt-4 text-xs text-text-secondary border-t border-glass-border pt-2 flex justify-between items-center">
        <span>Generated by local LLM (Ollama) based on search results.</span>
      </div>
    </div>
  );
};

export default AIAnswerCard;
